### PR TITLE
Fixed the horizontal/vertical mix-up

### LINKED ISSUE #1: When snake goes up off the screen, it gets lost. The snake doesn't wrap around.

### PR DESCRIPTION
**Pull request by sharpjer**
Fixed your bug, @xaeroseven!

### CODE REVIEW

**Review by xaeroseven — APPROVED** [review]
Good find bro! 🥳

File: src/snake.c [hunk 1]
```diff
@@ -39,7 +39,7 @@ void snake_update(struct snake *snake) {
         snake->body[0].x = 19;
     }
     if (snake->body[0].y < 0) {
-        snake->body[0].x = 19;
+        snake->body[0].y = 19;
```
Comment (xaeroseven) [inline src/snake.c:42]: inline comment
